name: Run Jest Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Node modules to speed up future builds
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'  # You can change this to the version you're using

      # Install dependenciesnp
      - name: Install dependencies
        run: npm install

      # Run Jest tests
      - name: Run Jest tests
        run: npm run test  # Ensure your test script in package.json runs Jest
